// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/v-escobar/game-api-go/internal/application"
	"github.com/v-escobar/game-api-go/internal/infrastructure/db"
	"github.com/v-escobar/game-api-go/internal/infrastructure/persistence"
	"github.com/v-escobar/game-api-go/internal/interfaces"
	"github.com/v-escobar/game-api-go/internal/interfaces/docs"
	"github.com/v-escobar/game-api-go/internal/interfaces/game"
)

import (
	_ "github.com/v-escobar/game-api-go/docs"
)

// Injectors from wire.go:

func initializeApp(dsn string) *App {
	gormDB := db.NewDB(dsn)
	repository := persistence.NewGameRepository(gormDB)
	gameService := application.NewGameService(repository)
	handler := game.NewGameHandler(gameService)
	documentationHandler := docs.NewDocumentationHandler()
	v := interfaces.NewHandlers(handler, documentationHandler)
	app := NewApp(v)
	return app
}
