on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      push-image:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        name: Setup Go
      - run: go mod download
        name: Go Mod Download
      - run: go test ./...
        name: Go Test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push-image }}
          tags: ghcr.io/vistiyos/game-api-go/${{ inputs.application }}:latest